[package]
name = "writeboost-cli"
version = "2.0.0"
authors = ["Akira Hayakawa <ruby.wktk@gmail.com>"]
edition = "2024"

[dependencies]
anyhow = "1"
byteorder = "1"
clap = { version = "4", features = ["derive"] }
crc = "3"
thiserror = "2.0.17"